# Generated by Django 5.1.4 on 2025-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremails',
            name='date_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
