# Generated by Django 5.1.4 on 2025-02-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useremails_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremails',
            name='registration_verification',
            field=models.BooleanField(default=True),
        ),
    ]
