# Generated by Django 5.1.4 on 2025-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useremails_verified_passwordresetemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetemails',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
