# Generated by Django 5.1.4 on 2024-12-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
