# Generated by Django 5.1.4 on 2025-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
